### ISSUE TITLE
Fix GitHub Pages

### ISSUE THREAD

**Issue by WashingtonBispo** [Interacao-Humano-Computador/2020.1-UVaJudge#4]
- [x] Fix GitHub Actions CI
- [ ] Swap images between Washington and Sergio

## Description

* Automate the deploy of mkdocs.
* Wrong images.

**Comment by SergioAlmeidaCiprianoJr** [comment]
While I was testing the CI on my fork , I realized that everything was already working fine. So, there is no need to fix Github Actions CI anymore.
